CREATE DATABASE IF NOT EXISTS core;
CREATE DATABASE IF NOT EXISTS cargador_dinamica;
CREATE DATABASE IF NOT EXISTS cargador_proxy;
CREATE DATABASE IF NOT EXISTS cargador_estatica;
CREATE DATABASE IF NOT EXISTS servicioestadisticas;